# Generated by Django 4.2.4 on 2023-09-13 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iznza', '0007_alter_users_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=240),
        ),
    ]
