# Generated by Django 4.2.4 on 2023-09-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iznza', '0010_users_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='birthday',
            field=models.DateField(max_length=120),
        ),
    ]
