# Generated by Django 4.2.4 on 2023-09-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iznza', '0012_remove_users_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='birthday',
        ),
        migrations.AddField(
            model_name='users',
            name='country',
            field=models.CharField(default='dddd', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='birth_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
