# Generated by Django 4.2.4 on 2023-09-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iznza', '0013_remove_users_birthday_users_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='birth_date',
            field=models.DateField(max_length=120),
        ),
    ]
