# Generated by Django 4.2.4 on 2023-09-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iznza', '0014_alter_users_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.CharField(auto_created=True, max_length=25, primary_key=True, serialize=False),
        ),
    ]
