# Generated by Django 4.2.4 on 2024-05-12 00:12

from django.db import migrations, models
import iznza.models


class Migration(migrations.Migration):

    dependencies = [
        ('iznza', '0021_rename_firstname_users_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.CharField(default=iznza.models.get_uuid, max_length=250, primary_key=True, serialize=False, unique=True),
        ),
    ]
