# Generated by Django 4.2.4 on 2024-05-12 00:15

from django.db import migrations, models
import iznza.models


class Migration(migrations.Migration):

    dependencies = [
        ('iznza', '0022_alter_users_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.CharField(default=iznza.models.get_uuid, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
