# Generated by Django 4.2.4 on 2023-09-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iznza', '0002_users_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=240),
        ),
    ]
