# Generated by Django 4.2.4 on 2023-09-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iznza', '0004_users_groups_users_is_active_users_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=240),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=240, unique=True),
        ),
    ]
