# Generated by Django 4.2.4 on 2023-09-13 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iznza', '0011_alter_users_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='country',
        ),
    ]
