# Generated by Django 4.2.4 on 2023-09-13 17:58

from django.db import migrations, models
import iznza.models


class Migration(migrations.Migration):

    dependencies = [
        ('iznza', '0016_alter_users_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.CharField(default=iznza.models.get_uuid, max_length=25, primary_key=True, serialize=False, unique=True),
        ),
    ]
