# Generated by Django 4.2.4 on 2023-11-13 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import iznza.models


class Migration(migrations.Migration):

    dependencies = [
        ('iznza', '0017_alter_users_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(default=iznza.models.get_uuid, max_length=25, primary_key=True, serialize=False, unique=True)),
                ('task', models.CharField(max_length=200)),
                ('isChecked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
