# Generated by Django 4.2.4 on 2024-05-07 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iznza', '0020_alter_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='firstName',
            new_name='fullName',
        ),
        migrations.RemoveField(
            model_name='users',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='users',
            name='country',
        ),
        migrations.RemoveField(
            model_name='users',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='users',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='users',
            name='registrationDate',
        ),
        migrations.AlterField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
